server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /test_db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/repo/KOTLIN-SPRING/test_db;AUTO_SERVER=TRUE
    username: jinhan
    password: 1234